### ISSUE TITLE
Program fails to start, event 1023

### ISSUE THREAD

**Issue by RiggiG** [noahtheprogrammer/saltyminer#15]
Using v1.2.2 hotfix
Windows 10 Pro 20H2 19042.1348 
.NET desktop runtime 3.1.21-win-x86 installed
```
An assembly specified in the application dependencies manifest (salty.deps.json) was not found:
    package: 'Microsoft.Win32.Registry', version: '5.0.0'
    path: 'runtimes/win/lib/netstandard2.0/Microsoft.Win32.Registry.dll'
```

**Comment by noahtheprogrammer** [comment]
Hello, has this been happening on the latest version with the hot fix?

**Comment by RiggiG** [comment]
Yep, apologies - added that in an edit just before you responded.

**Comment by noahtheprogrammer** [comment]
I believe something got corrupted while I was updating the frameworks, and can't find out where it occurred. I think I'm going to make this version obsolete and develop on WPF instead of WinForms.

**Comment by noahtheprogrammer** [comment]
If you would be interested in helping I can make you a collaborator.

**Comment by noahtheprogrammer** [comment]
I am going to be building on the .NET 5.0 Framework, instead of .NET 3.1 with LTS.
